
OBJEXT ?=o
OBJEXTG=lo
# Module Dependencies:
gghh_smehc_test.mod: test.$(OBJEXTG)
gghh_smehc_matrix.mod: matrix.$(OBJEXTG)
test.$(OBJEXT): matrix.$(OBJEXT)
matrix.$(OBJEXT): matrix.$(OBJEXTG)
../matrix/libgolem_process_gghh_smehc_matrix.la: libgolem_process_gghh_smehc_matrix.la
