# vim: ts=3:sw=3

OBJEXT ?=o
OBJEXTG=lo
# Module Dependencies:
abbrevd9h0.$(OBJEXTG): globals.$(OBJEXTG)
d9h0l1.$(OBJEXTG): abbrevd9h0.$(OBJEXTG)
d9h0l1d.$(OBJEXTG): abbrevd9h0.$(OBJEXTG)
abbrevd25h0.$(OBJEXTG): globals.$(OBJEXTG)
d25h0l1.$(OBJEXTG): abbrevd25h0.$(OBJEXTG)
d25h0l1d.$(OBJEXTG): abbrevd25h0.$(OBJEXTG)
abbrevd26h0.$(OBJEXTG): globals.$(OBJEXTG)
d26h0l1.$(OBJEXTG): abbrevd26h0.$(OBJEXTG)
d26h0l1d.$(OBJEXTG): abbrevd26h0.$(OBJEXTG)
abbrevd37h0.$(OBJEXTG): globals.$(OBJEXTG)
d37h0l1.$(OBJEXTG): abbrevd37h0.$(OBJEXTG)
d37h0l1d.$(OBJEXTG): abbrevd37h0.$(OBJEXTG)
ninjah0.$(OBJEXTG):  \
	d9h0l1.$(OBJEXTG) d9h0l131.$(OBJEXTG) d9h0l132.$(OBJEXTG) d9h0l121.$(OBJEXTG) \
	d25h0l1.$(OBJEXTG) d25h0l131.$(OBJEXTG) d25h0l132.$(OBJEXTG) d25h0l121.$(OBJEXTG) \
	d26h0l1.$(OBJEXTG) d26h0l131.$(OBJEXTG) d26h0l132.$(OBJEXTG) d26h0l121.$(OBJEXTG) \
	d37h0l1.$(OBJEXTG) d37h0l131.$(OBJEXTG) d37h0l132.$(OBJEXTG) d37h0l121.$(OBJEXTG)
d9h0l131.$(OBJEXTG): abbrevd9h0.$(OBJEXTG)
d9h0l132.$(OBJEXTG): abbrevd9h0.$(OBJEXTG)
d9h0l121.$(OBJEXTG): abbrevd9h0.$(OBJEXTG)
d25h0l131.$(OBJEXTG): abbrevd25h0.$(OBJEXTG)
d25h0l132.$(OBJEXTG): abbrevd25h0.$(OBJEXTG)
d25h0l121.$(OBJEXTG): abbrevd25h0.$(OBJEXTG)
d26h0l131.$(OBJEXTG): abbrevd26h0.$(OBJEXTG)
d26h0l132.$(OBJEXTG): abbrevd26h0.$(OBJEXTG)
d26h0l121.$(OBJEXTG): abbrevd26h0.$(OBJEXTG)
d37h0l131.$(OBJEXTG): abbrevd37h0.$(OBJEXTG)
d37h0l132.$(OBJEXTG): abbrevd37h0.$(OBJEXTG)
d37h0l121.$(OBJEXTG): abbrevd37h0.$(OBJEXTG)
amplitudeh0.$(OBJEXTG): globals.$(OBJEXTG) diagramsl0.$(OBJEXTG) ninjah0.$(OBJEXTG) \
			diagramsl0.$(OBJEXTG) \
			abbrevd9h0.$(OBJEXTG) \
			abbrevd25h0.$(OBJEXTG) \
			abbrevd26h0.$(OBJEXTG) \
			abbrevd37h0.$(OBJEXTG)
gghh_smehc_diagramsh0l0.mod: diagramsl0.$(OBJEXTG)
gghh_smehc_d1h0l0.mod: d1h0l0.$(OBJEXTG)
gghh_smehc_ninjah0.mod: ninjah0.$(OBJEXTG) 
gghh_smehc_d9h0l131.mod: d9h0l131.$(OBJEXTG)
gghh_smehc_d9h0l132.mod: d9h0l132.$(OBJEXTG)
gghh_smehc_d9h0l121.mod: d9h0l121.$(OBJEXTG)
gghh_smehc_d25h0l131.mod: d25h0l131.$(OBJEXTG)
gghh_smehc_d25h0l132.mod: d25h0l132.$(OBJEXTG)
gghh_smehc_d25h0l121.mod: d25h0l121.$(OBJEXTG)
gghh_smehc_d26h0l131.mod: d26h0l131.$(OBJEXTG)
gghh_smehc_d26h0l132.mod: d26h0l132.$(OBJEXTG)
gghh_smehc_d26h0l121.mod: d26h0l121.$(OBJEXTG)
gghh_smehc_d37h0l131.mod: d37h0l131.$(OBJEXTG)
gghh_smehc_d37h0l132.mod: d37h0l132.$(OBJEXTG)
gghh_smehc_d37h0l121.mod: d37h0l121.$(OBJEXTG)
gghh_smehc_abbrevd9h0.mod: abbrevd9h0.$(OBJEXTG)
gghh_smehc_d9h0l1.mod: d9h0l1.$(OBJEXTG)
gghh_smehc_d9h0l1d.mod: d9h0l1d.$(OBJEXTG)
gghh_smehc_abbrevd25h0.mod: abbrevd25h0.$(OBJEXTG)
gghh_smehc_d25h0l1.mod: d25h0l1.$(OBJEXTG)
gghh_smehc_d25h0l1d.mod: d25h0l1d.$(OBJEXTG)
gghh_smehc_abbrevd26h0.mod: abbrevd26h0.$(OBJEXTG)
gghh_smehc_d26h0l1.mod: d26h0l1.$(OBJEXTG)
gghh_smehc_d26h0l1d.mod: d26h0l1d.$(OBJEXTG)
gghh_smehc_abbrevd37h0.mod: abbrevd37h0.$(OBJEXTG)
gghh_smehc_d37h0l1.mod: d37h0l1.$(OBJEXTG)
gghh_smehc_d37h0l1d.mod: d37h0l1d.$(OBJEXTG)
gghh_smehc_amplitudeh0.mod: amplitudeh0.$(OBJEXTG)
gghh_smehc_globalsh0.mod: globals.$(OBJEXTG)
